"""Second visual direction: bold NGO presentation and an extensive photo archive."""
import json

def install(g):
    esc,link,photo,badge=g['esc'],g['link'],g['photo'],g['badge']
    photos=g['PHOTOS'];keys=json.loads((g['ROOT']/'gallery.json').read_text())
    def img(key,cls='',eager=False):
        item=photos[key];versions=item['variants'];src=g['prefix']()+'assets/'+versions[-1]['file']
        ss=', '.join(g['prefix']()+'assets/'+v['file']+' '+str(v['width'])+'w' for v in versions)
        return f'<img class="{cls}" src="{src}" srcset="{ss}" sizes="{'100vw' if cls in ('v2-hero-photo','v2-page-backdrop','v2-closing-image') else '(max-width: 650px) 100vw, (max-width: 1000px) 50vw, 33vw'}" width="{item["width"]}" height="{item["height"]}" alt="{esc(item["alt"])}" loading="{"eager" if eager else "lazy"}" decoding="async">'
    def tile(key):return '<div class="v2-photo-tile">'+img(key)+'</div>'
    def pillars():
        out='<div class="v2-pillars">'
        descriptions=['Practical digital skills and opportunities to learn.','Building on health-related community work.','Future pathways for skills and livelihood.','Food and clothing support, rooted in community.','Planned care for our shared surroundings.','Dignity, inclusion and community awareness.']
        for i,(name,slug,status,_,_) in enumerate(g['PILLARS']):
            out+=f'<a class="v2-pillar" data-route="/our-work/{slug}" href="{g["href"]("/our-work/"+slug)}"><span class="v2-pillar-number">0{i+1}</span>{badge(status)}<h3>{esc(name)}</h3><p>{descriptions[i]}</p><span class="v2-small-link">Discover this area</span></a>'
        return out+'</div>'
    def stories():
        out='<div class="v2-stories story-grid">'
        for key,title,body,dest in [('community-together','From Bharosa to Aashray','How a lockdown food response became a wider community mission.','/about-us'),('roti-contribution','The Roti Challenge','The story of families, volunteers and a weekly contribution of care.','/roti-challenge')]:
            out+='<article class="story-card">'+img(key)+'<div class="v2-story-copy"><span class="eyebrow">OUR COMMUNITY STORY</span><h3>'+title+'</h3><p>'+body+'</p>'+link('Read the story',dest)+'<p class="photo-context">Photograph from the wider organisation collection, not a dated record of 2020.</p></div></article>'
        return out+'</div>'
    def gallery():
        categories=['All photographs','Food preparation','Community outreach','People & participation']
        out='<section class="v2-archive"><span class="eyebrow">OUR PHOTO COLLECTION</span><h2>See the community<br>behind the work.</h2><p>Explore 80 photographs supplied by the organisation. Dates and individual activity details are being documented.</p><div class="v2-gallery-filters" role="group" aria-label="Photo categories">'+''.join(f'<button type="button" data-photo-category="{esc(c)}" aria-pressed="{"true" if i==0 else "false"}">{esc(c)}</button>' for i,c in enumerate(categories))+'</div><p class="gallery-count" aria-live="polite"></p><div class="v2-gallery">'
        for key in keys:
            p=photos[key]
            out+=f'<button type="button" class="gallery-photo" data-group="{esc(p["category"])}" data-photo="{g["prefix"]()}assets/{p["variants"][-1]["file"]}" data-alt="{esc(p["alt"])}" data-caption="{esc(p["caption"])}" aria-label="Enlarge photograph: {esc(p["alt"])}">'+img(key)+'<span>'+esc(p['caption'])+'</span><span class="enlarge-label">View photograph</span></button>'
        return out+'</div><button type="button" class="button primary gallery-more" hidden>Show more photographs</button><dialog id="photo-viewer" aria-label="Enlarged organisation photograph"><button type="button" class="viewer-close" aria-label="Close enlarged photograph">Close ×</button><img alt=""><p></p></dialog></section>'
    def hero(page):
        route=page['route'];lines=g['section'](page,'Hero')['lines'];title=lines[0] if lines else page['name'];status=g['status_for'](route)
        mapping={'/about-us':'community-together','/our-work':'volunteers-together','/our-work/community-relief':'community-outreach','/roti-challenge':'meal-packing','/impact-stories':'community-together','/get-involved':'volunteers-together','/volunteer':'food-preparation','/partner-with-us':'team-conversation','/support-our-work':'meal-packing','/contact':'volunteers-together'}
        key=mapping.get(route)
        out='<section class="v2-page-hero '+('with-image' if key else 'without-image')+'">'
        if key:out+=img(key,'v2-page-backdrop',True)
        out+='<div class="container"><div class="breadcrumb">'+link('Home','/','')+'<span>/</span>'+esc(page['name'].replace(' and ',' & '))+'</div><div class="v2-page-title"><p class="eyebrow">'+esc(page['name'].replace(' and ',' & '))+'</p>'+(badge(status) if status else '')+'<h1>'+esc(title)+'</h1>'+g['paragraphs']([x for x in lines[1:] if not x.startswith('Button  ')])+g['buttons'](lines)+'</div></div></section>'
        return out
    def home():
        p=g['BY_ROUTE']['/'];sec=lambda h:g['section'](p,h)['lines']
        out='<section class="v2-home-hero" aria-label="Aashray introduction"><div class="v2-hero-slides">'
        for i,key in enumerate(['community-together','meal-packing','community-outreach']):out+=f'<div class="v2-hero-slide {"is-current" if i==0 else ""}" data-slide="{i}" aria-hidden="{"false" if i==0 else "true"}">'+img(key,'v2-hero-photo',i==0)+'</div>'
        out+='</div><div class="container v2-hero-content"><p class="eyebrow">SILIGURI AASHRAY WELFARE FOUNDATION</p><h1>Aashray for Hope.<br>Aashray for Dignity.<br><span>Aashray for Everyone.</span></h1><p>'+esc(sec('Hero')[1])+'</p>'+g['buttons'](sec('Hero'))+'</div><div class="container v2-hero-bottom"><span>COMMUNITY CARE. SHARED RESPONSIBILITY.</span><div class="v2-slide-controls" role="group" aria-label="Hero photographs">'+''.join(f'<button type="button" class="{"active" if i==0 else ""}" data-select-slide="{i}" aria-label="Show photograph {i+1}" aria-pressed="{"true" if i==0 else "false"}">0{i+1}</button>' for i in range(3))+'</div></div></section>'
        out+='<section class="v2-origin section"><div class="container v2-split"><div class="v2-collage">'+tile('community-together')+tile('roti-contribution')+tile('shared-kitchen')+'<p>From the wider organisation photo collection.</p></div><div><p class="eyebrow">OUR STORY BEGAN IN 2020</p><h2>Small acts.<br><span>A shared beginning.</span></h2><p class="v2-lead">'+esc(sec('Our story began in 2020')[0])+'</p>'+'<p>What began as Bharosa Group grew through the Roti Challenge: families and volunteers sharing responsibility for a meal.</p><div class="story-thread"><span>Bharosa Group<small>Our beginning · 2020</small></span><span>Roti Challenge<small>A shared weekly effort</small></span><span>Aashray<small>A wider community vision</small></span></div>'+g['buttons'](sec('Our story began in 2020'))+'</div></div></section>'
        out+='<section class="section v2-work"><div class="container"><div class="v2-section-intro"><div><p class="eyebrow">OUR SIX IMPACT AREAS</p><h2>Care for today.<br><span>Opportunity for tomorrow.</span></h2></div><p>'+esc(sec('Our six impact areas')[0])+'</p></div>'+pillars()+'</div></section>'
        out+='<section class="section v2-progress"><div class="container v2-split"><div><p class="eyebrow">OUR WORK AND NEXT STEPS</p><h2>Building on<br>the work we began.</h2>'+'<p>Food distribution, clothing distribution and health-related work form part of our journey.</p><p>Computer training is an upcoming program. Women &amp; Livelihood, Environment &amp; Animal Welfare, and Human Rights are planned initiatives.</p>'+g['buttons'](sec('Our work and next steps'))+'</div><div class="v2-progress-pictures">'+tile('community-outreach')+tile('food-preparation')+tile('packed-meals')+'</div></div></section>'
        out+='<section class="section v2-roti"><div class="container v2-split"><div class="v2-roti-images">'+photo('roti-contribution',caption=True)+tile('meal-packing')+'</div><div><p class="eyebrow">THE ROTI CHALLENGE</p>'+badge('Legacy initiative')+'<h2>Many kitchens.<br><span>One community.</span></h2><p class="v2-lead">'+esc(sec('Roti Challenge')[0])+'</p>'+'<p>A weekly contribution from home became a collective act of care. Families prepared rotis, and the team brought the meals together for distribution.</p>'+g['buttons'](sec('Roti Challenge'))+'</div></div><div class="container roti-five"><p class="eyebrow">HOW THE ROTI CHALLENGE WORKED</p><h3>From one kitchen to <em>many hands.</em></h3><ol><li><strong>Join the weekly effort</strong><p>Participating families contribute rotis once a week.</p></li><li><strong>Prepare at home</strong><p>Families prepare their contribution in their own kitchens.</p></li><li><strong>Collect with care</strong><p>Volunteers collect the rotis from participating homes.</p></li><li><strong>Bring the meal together</strong><p>Food is packed at the team’s work location.</p></li><li><strong>Share a meal</strong><p>The team goes out to distribute the meals.</p></li></ol></div></section>'
        mosaic=['meal-packing','community-outreach','food-preparation','volunteers-together','food-parcels','sharing-refreshments']
        out+='<section class="section v2-home-archive"><div class="container"><div class="v2-section-intro"><div><p class="eyebrow">THE IMPACT ARCHIVE</p><h2>Real people.<br><span>Real participation.</span></h2></div><div>'+g['paragraphs'](sec('Impact and stories')[1:])+link('Explore all 80 photographs','/impact-stories','button primary')+'</div></div><div class="v2-mosaic">'+''.join(tile(k) for k in mosaic)+'</div></div></section>'
        out+='<section class="section v2-community-stories"><div class="container"><p class="eyebrow">STORIES FROM THE COMMUNITY</p><h2>How our story<br><span>became a shared journey.</span></h2>'+stories()+'</div></section>'
        out+='<section class="section v2-involve"><div class="container"><div class="v2-section-intro"><div><p class="eyebrow">GET INVOLVED</p><h2>Your time. Your skills.<br><span>Your part in the story.</span></h2></div><div>'+g['paragraphs'](sec('Get involved')[1:])+g['buttons'](sec('Get involved'))+'</div></div><div class="v2-participation-grid">'+''.join('<article>'+img(k)+'<h3>'+title+'</h3>'+link(label,url)+'</article>' for k,title,label,url in [('shared-kitchen','Give your time','Become a Volunteer','/volunteer'),('team-conversation','Bring your experience','Partner With Us','/partner-with-us'),('food-supplies','Contribute with care','Support Our Work','/support-our-work')])+'</div></div></section>'
        out+='<section class="section v2-partnership"><div class="container v2-split">'+photo('team-conversation',caption=True)+'<div><p class="eyebrow">WORKING TOGETHER</p><h2>Good work grows<br><span>when we come together.</span></h2>'+g['paragraphs'](sec('Working together'))+g['buttons'](sec('Working together'))+'</div></div></section>'
        out+='<section class="section v2-trust"><div class="container v2-section-intro"><div><p class="eyebrow">TRANSPARENCY AND TRUST</p><h2>Trust begins<br>with openness.</h2></div><div>'+g['paragraphs'](sec('Transparency and trust')[1:])+g['buttons'](sec('Transparency and trust'))+'</div></div></section>'
        out+='<section class="section v2-closing">'+img('volunteers-together','v2-closing-image')+'<div class="container"><p class="eyebrow">BE PART OF WHAT COMES NEXT</p><h2>'+esc(sec('Closing invitation')[0])+'</h2>'+g['paragraphs'](sec('Closing invitation')[1:])+g['buttons'](sec('Closing invitation'))+'</div></section>'
        return out
    g.update(home=home,hero=hero,cards=pillars,story_cards=stories,photo_gallery=gallery)
